### ISSUE TITLE
your game sucks

### ISSUE THREAD

**Issue by ExpressGradient** [macklark/Vue-ticTtoe#1]
it lacks logic

**Comment by macklark** [comment]
Will fix shortly

**Comment by ExpressGradient** [comment]
hmm

**Comment by macklark** [comment]
Hey, Checkout my code I made some fixes, I guess.

**Comment by ExpressGradient** [comment]
Great, you still haven't locked the game from further playing.

**Comment by macklark** [comment]
I Will today and add the modal

**Comment by macklark** [comment]
bug solved !
